### ISSUE TITLE
Unable to Analyze WebLogic Access Log

### ISSUE THREAD

**Issue by saurbh-m** [makeyourownmaker/apache-response-time#4]
Hi,

I'm trying to analyze an access log of Oracle WebLogic Server. The output I'm getting is: "No matches in access log!".

Please find the attached log which contains the header of the actual log.

[sample.log](https://github.com/makeyourownmaker/apache-response-time/files/1681270/sample.log)

**Comment by makeyourownmaker** [comment]
Hi saurbh-m

The apache-response-time script is now fairly mature.  I've not made any major changes to it for years.  Also, I've unsubscribed from github issues for it.  

If you still want to use the script then you'll have to transform the Oracle WebLogic Server log file to the apache log file format, which is documented here: http://httpd.apache.org/docs/current/mod/mod_log_config.html

You could probably do this with an awk or perl one-liner.

Hope this helps.
